-- sales_queries.sql

-- 1. Best-selling items
SELECT 
    i.description AS ItemDescription,
    SUM(s.quantity) AS TotalSold
FROM 
    Sales s
JOIN 
    Items i ON s.item_id = i.item_id
GROUP BY 
    i.description
ORDER BY 
    TotalSold DESC;

-- 2. Total revenue generated by each item
SELECT 
    i.description AS ItemDescription,
    SUM(s.quantity * s.price) AS TotalRevenue
FROM 
    Sales s
JOIN 
    Items i ON s.item_id = i.item_id
GROUP BY 
    i.description
ORDER BY 
    TotalRevenue DESC;

-- 3. Customers with the most purchases
SELECT 
    c.customer_name AS CustomerName,
    COUNT(s.sale_id) AS NumberOfPurchases
FROM 
    Sales s
JOIN 
    Customers c ON s.customer_id = c.customer_id
GROUP BY 
    c.customer_name
ORDER BY 
    NumberOfPurchases DESC;

-- 4. Items not sold in the last 6 months
SELECT 
    i.description AS ItemDescription
FROM 
    Items i
LEFT JOIN 
    Sales s ON i.item_id = s.item_id AND s.date_sold >= CURDATE() - INTERVAL 6 MONTH
WHERE 
    s.sale_id IS NULL;
